language: java
jdk:
- openjdk11



addons:
  sonarcloud:
    organization: "riccardoburaioli" 
    token: 
	secure:"cd4c43a0c8d5e1ad0fbf651c78c8e149c38f3358"

script:
- ant build
- sonar-scanner
